export const SERVICES = [
  {
    id: "cosmetic",
    title: "Cosmetic Dentistry",
    subtitle: "Transform your smile with our advanced cosmetic dental treatments",
    icon: "✦",
    description: "Enhance your smile with professional teeth whitening, veneers, bonding, and total smile makeovers.",
    image: "3cde425874df775c67d52ded6a3a93d7a0b21122.png",
    intro: "There has been a dramatic interest in cosmetic dentistry. We all understand that having a healthy, bright, and beautiful smile enhances our appearance and allows us to smile with confidence. Thanks to the advances in modern cosmetic dentistry, we are able to improve our teeth and smiles with quick, painless and surprisingly affordable treatments that do not destroy the underlying healthy tooth structure!",
    sectionTitle: "Our Cosmetic Procedures",
    procedures: [
      { title: "Composite Fillings", desc: "Tooth-colored fillings that blend naturally with your smile" },
      { title: "Crowns or Caps", desc: "Restore and protect damaged teeth with natural-looking crowns" },
      { title: "Inlays", desc: "Custom-made restorations for conservative tooth repair" },
      { title: "Onlays", desc: "Partial crowns that preserve healthy tooth structure" },
      { title: "Teeth Whitening", desc: "Professional whitening for a brighter, more confident smile" },
      { title: "Veneers", desc: "Ultra-thin porcelain shells to reshape and perfect your smile" },
      { title: "Dental Bonding", desc: "Composite resin applied to repair chips, cracks or gaps" },
      { title: "Smile Makeover", desc: "Comprehensive plan combining multiple cosmetic treatments" },
    ],
    accordions: [],
  },
  {
    id: "general",
    title: "General Dentistry",
    subtitle: "Comprehensive preventive care to preserve your natural teeth and maintain optimal oral health",
    icon: "",
    description: "Comprehensive care including routine cleanings, fillings, digital x-rays, and preventative treatments.",
    image: "a2a139a78dd7a6baafa9c2eea9cbc0d88ca734e5.png",
    intro: "A preventive program is a cooperative effort by the patient, dentist, and dental team to preserve the natural dentition and supporting structures by preventing the onset, progress, and recurrence of dental diseases and conditions. At Heritage Oak Dental we want to preserve your natural dentition because we know it will provide you the best long term service when compared to even the most modern restorative dental procedures.",
    sectionTitle: "",
    procedures: [],
    accordions: [
      {
        title: "Dental X-Rays",
        content: "X-rays (Dental Radiographs) are essential, preventative, diagnostic tools that provide valuable information not visible during a regular dental exam. Dentists and dental hygienists use this information to safely and accurately detect hidden dental abnormalities and complete an accurate treatment plan. Without x-rays, problem areas would go undetected until the problem was causing greater damage.\n\nDental Radiographs help reveal: Abscesses or cysts, Bone loss, Cancerous and non-cancerous tumors, Decay between the teeth, Developmental abnormalities, Poor tooth and root positions, Problems inside a tooth or below the gum line.\n\nDetecting and treating dental problems at an early stage can save you time, money, unnecessary discomfort, and your teeth. Your dentist and dental hygienist will recommend necessary x-rays based on the review of your medical and dental history, dental exam, signs and symptoms, age consideration, and risk for disease.\n\nA full mouth series of dental x-rays is recommended for new patients. A full series is usually good for three to five years. Bite-wing x-rays are taken at recall (check-up) visits and are recommended once or twice a year to detect new dental problems.",
        callout: {
          title: "What if I'm pregnant?",
          text: "A radiograph may be needed for dental treatment that can't wait until after the baby is born. Because untreated dental infections can pose a risk to the fetus, dental treatment may be necessary. A leaded apron minimizes exposure to the abdomen and should be used when any dental radiograph is taken. A leaded thyroid collar can also protect the thyroid from radiation.",
        },
      },
      { title: "Digital X-Rays", content: "Digital x-rays use up to 90% less radiation than conventional film x-rays while producing immediate, high-quality images. These images can be enhanced and enlarged on a computer monitor for more accurate diagnosis.", callout: null },
      { title: "3D Imaging (CBCT Scans)", content: "Cone Beam Computed Tomography (CBCT) provides three-dimensional images of teeth, soft tissues, nerve pathways, and bone in a single scan. This advanced imaging is essential for dental implant planning, evaluating jawbone structure, and diagnosing complex dental and facial problems.", callout: null },
      { title: "Dental Exams & Cleanings", content: "Regular dental exams and cleanings are essential to maintaining good oral health. During your exam, Dr. Douglas or Dr. Kloss will evaluate your teeth, gums, and overall oral health. Professional cleanings remove plaque and tartar buildup that regular brushing and flossing cannot remove.", callout: null },
      { title: "Oral Cancer Exam", content: "Oral cancer screening is a routine part of your dental examination. Early detection is key to successful treatment. Our team will check your mouth, throat, tongue, and lips for any signs of abnormal tissue or other indicators of oral cancer.", callout: null },
      { title: "Fluoride Treatment", content: "Fluoride is the most effective agent available to help prevent tooth decay. It is a mineral that is naturally present in varying amounts in almost all foods and water supplies. The benefits of fluoride have been well known for over 50 years and are supported by many health and professional organizations.", callout: null },
      { title: "Sealants", content: "Dental sealants act as a barrier to prevent cavities. They are a plastic material usually applied to the chewing surfaces of the back teeth (premolars and molars) where decay occurs most often. Thorough brushing and flossing help remove food particles and plaque from smooth surfaces of teeth. But toothbrush bristles cannot reach all the way into the depressions and grooves to extract food and plaque.", callout: null },
    ],
  },
  {
    id: "implant",
    title: "Implant Dentistry",
    subtitle: "Restore missing teeth permanently with state-of-the-art dental implants",
    icon: "",
    description: "Restore missing teeth permanently with state-of-the-art dental implants that look and function naturally.",
    image: "15961fd957b74c5f14cca9c8d81747c437d0734d.png",
    intro: "Dental implants are changing the way people live. With them, people are rediscovering the comfort and confidence to eat, speak, laugh, and enjoy life. Implants are the new standard for replacing missing teeth because they look, feel, and function like natural teeth. They are a permanent solution designed to last a lifetime with proper care.",
    sectionTitle: "Implant Services",
    procedures: [
      { title: "Single Tooth Implant", desc: "Replace one missing tooth with a natural-looking implant crown" },
      { title: "Multiple Teeth Implants", desc: "Restore several missing teeth individually without affecting adjacent teeth" },
      { title: "Implant-Supported Bridge", desc: "A bridge anchored by implants rather than natural teeth" },
      { title: "All-on-4 / Full Arch Restoration", desc: "Full arch restoration using just four strategically placed implants" },
    ],
    accordions: [],
  },
  {
    id: "oral-surgery",
    title: "Oral & Maxillofacial Surgery",
    subtitle: "Expert surgical care performed with precision and compassion",
    icon: "",
    description: "Expert surgical care including extractions, wisdom teeth removal, and advanced jaw procedures.",
    image: "9b17b9cbf8d3f97c920e9b9f9cf4ef0116050ffe.png",
    intro: "Our oral surgery services are performed by experienced professionals using the latest techniques and technology to ensure your safety and comfort. From simple extractions to complex wisdom tooth removal, we will walk you through the entire process and make sure you feel informed and at ease.",
    sectionTitle: "Oral Surgery Services",
    procedures: [
      { title: "Tooth Extractions", desc: "Safe, gentle removal of damaged or problematic teeth" },
      { title: "Wisdom Teeth Removal", desc: "Expert extraction of impacted or problematic wisdom teeth" },
      { title: "Bone Grafting", desc: "Rebuild bone structure to support future implants or restorations" },
      { title: "Socket Preservation", desc: "Protect the tooth socket after extraction to maintain bone volume" },
    ],
    accordions: [],
  },
  {
    id: "orthodontics",
    title: "Orthodontics",
    subtitle: "Straighten your smile with modern orthodontic solutions",
    icon: "",
    description: "Straighten your smile with traditional braces, clear ceramic braces, or invisible aligners like Invisalign.",
    image: "7eecb1f239c1d2471a87cf1669a5e0420ec9aa6b.png",
    intro: "Orthodontic treatment is not just for kids. Adults of all ages are discovering the benefits of a straighter, more beautiful smile. With advances in orthodontic technology, there are more options than ever to achieve the smile you've always wanted — discreetly, comfortably, and efficiently.",
    sectionTitle: "Orthodontic Options",
    procedures: [
      { title: "Traditional Braces", desc: "Time-tested metal braces for effective teeth alignment" },
      { title: "Clear Ceramic Braces", desc: "Tooth-colored brackets that blend with your smile" },
      { title: "Invisalign", desc: "Virtually invisible removable aligners for a discreet treatment" },
      { title: "Retainers", desc: "Custom retainers to maintain your results after treatment" },
    ],
    accordions: [],
  },
  {
    id: "pediatric",
    title: "Pediatric Dentistry",
    subtitle: "Gentle, friendly dental care for your children",
    icon: "",
    description: "Specialized gentle dental care tailored for children of all ages, making every visit comfortable and fun.",
    image: "db6e50499d0e50178856effaf7fc05fb9fdf2230.png",
    intro: "At Heritage Oak Dental, we love seeing our younger patients. We've created a warm, welcoming environment with a dedicated kids' play area to help children feel at ease. Our goal is to make dental visits fun and positive, establishing healthy habits that last a lifetime.",
    sectionTitle: "Children's Dental Services",
    procedures: [
      { title: "Children's Exams & Cleanings", desc: "Gentle, thorough cleanings and exams for growing smiles" },
      { title: "Fluoride Treatments", desc: "Protect young teeth from decay with professional fluoride" },
      { title: "Sealants", desc: "Protective coating to prevent cavities in back molars" },
      { title: "Early Orthodontic Evaluation", desc: "Assess bite and jaw development to plan future treatment" },
    ],
    accordions: [],
  },
  {
    id: "periodontics",
    title: "Periodontics",
    subtitle: "Protect your gums and the foundation of your smile",
    icon: "",
    description: "Expert gum care including scaling, root planing, and periodontal maintenance to keep your gums healthy.",
    image: "2726a6c67356db00995357e7fc60d2e1135365b8.png",
    intro: "Periodontal disease is a serious infection of the gums and bone that support your teeth. It is the leading cause of tooth loss in adults. Early treatment is essential to controlling the disease and preventing more serious consequences. Our team provides comprehensive periodontal care to keep your gums healthy.",
    sectionTitle: "Periodontal Services",
    procedures: [
      { title: "Periodontal Evaluation", desc: "Thorough assessment of your gum health and bone levels" },
      { title: "Scaling & Root Planing", desc: "Deep cleaning to remove tartar below the gumline" },
      { title: "Periodontal Maintenance", desc: "Regular cleanings to keep gum disease under control" },
      { title: "Laser Gum Therapy", desc: "Advanced laser treatment for precision and faster healing" },
    ],
    accordions: [],
  },
  {
    id: "restorative",
    title: "Restorative Dentistry",
    subtitle: "Rebuild your smile with natural-looking restorations",
    icon: "",
    description: "Restore damaged or missing teeth with natural-looking crowns, bridges, dentures, and fillings.",
    image: "a2a139a78dd7a6baafa9c2eea9cbc0d88ca734e5.png",
    intro: "At Heritage Oak Dental, our goal is to restore your teeth to their natural appearance and function. Whether you have a single damaged tooth or need a complete smile makeover, our restorative dental services are designed to give you a healthy, beautiful smile that lasts.",
    sectionTitle: "Restorative Services",
    procedures: [
      { title: "Composite Fillings", desc: "Tooth-colored fillings to repair cavities while preserving your natural look" },
      { title: "Dental Crowns", desc: "Custom-made caps that restore damaged or weakened teeth" },
      { title: "Dental Bridges", desc: "Fixed restorations that replace one or more missing teeth" },
      { title: "Dentures & Partials", desc: "Removable replacements for multiple missing teeth" },
      { title: "Inlays & Onlays", desc: "Conservative restorations for moderately damaged back teeth" },
      { title: "Root Canal Therapy", desc: "Save an infected or damaged tooth by treating the inner pulp" },
    ],
    accordions: [],
  },
  {
    id: "sedation",
    title: "Sedation Dentistry",
    subtitle: "Relax and feel comfortable during your dental treatment",
    icon: "",
    description: "Experience relaxed, anxiety-free visits with safe and effective oral and nitrous sedation options.",
    image: "e4399d2ba7b7964ecb0957ba49aacd49239fdb72.png",
    intro: "Do you feel anxious or fearful about dental appointments? You are not alone. Dental anxiety affects millions of people. At Heritage Oak Dental, we offer several sedation options to help you feel calm and comfortable throughout your treatment — so you can get the care you need without the worry.",
    sectionTitle: "Sedation Options",
    procedures: [
      { title: "Nitrous Oxide (Laughing Gas)", desc: "Inhaled sedation that produces a calm, relaxed feeling during treatment" },
      { title: "Oral Conscious Sedation", desc: "Oral medication taken before your appointment to reduce anxiety" },
      { title: "IV Sedation", desc: "Deeper sedation administered intravenously for complex procedures" },
    ],
    accordions: [],
  },
];

export const RESOURCES = [
  { id: "newpatient", title: "New Patient Forms" },
  { id: "finance", title: "Finance" },
  { id: "pretreatment", title: "Pre-Treatment Instructions" },
  { id: "posttreatment", title: "Post-Treatment Instructions" },
];

export const TEAM = [
  {
    id: "shane-douglas",
    name: "Dr. Shane Douglas",
    role: "Lead Dentist",
    image: "dr-douglas.png",
    bio: "Dr. Shane Douglas is committed to providing exceptional dental care with a gentle touch. He continually invests in advanced education to bring the latest techniques and technologies to Heritage Oak Dental."
  },
  {
    id: "ben-kloss",
    name: "Dr. Ben Kloss",
    role: "Associate Dentist",
    image: "dr-kloss.png",
    bio: "Dr. Ben Kloss focuses on patient comfort and comprehensive care. His personalized approach ensures every patient feels heard and receives treatments tailored to their specific oral health goals."
  }
];
